### PR TITLE
Use comments as field description

### PR DESCRIPTION
**Pull request by chuhlomin**
This PR adds a fields description based on a comments in proto-files (unless they have a custom option `BigQueryFieldOptions.Description` defined).

### CODE REVIEW

**Comment by sdotz** [comment]
Would love to see this reviewed and merged! We've used this great plugin, plus the code here to generate our BQ schema @ The New York Times. Our protobuf schema is used for generating lots of things in addition to the BQ schema, and so we store all of the field descriptions unobtrusively in comments. We would love to hear about any feedback/improvements as it seems pretty common thing to document .proto fields with comments. Thanks!

**Comment by chuhlomin** [comment]
@yugui Could you please give a review?

**Comment by brucearctor** [comment]
Was just looking at writing some similar functionality -- any reason this hasn't gotten reviewed/merged?  Other thoughts/approaches that are more sensible?  @yugui , @chuhlomin ?  What did you wind up using as a solution @sdotz ?

**Comment by chuhlomin** [comment]
It seems like this repo is not actively maintained.
I ended up forking it: https://github.com/chuhlomin/protoc-gen-bq-schema/tree/develop
And providing Docker image: https://hub.docker.com/repository/docker/chuhlomin/protoc-gen-bq-schema

**Comment by sdotz** [comment]
I’m using the @chuhlomin fork

**Comment by brucearctor** [comment]
Awesome, thanks!

**Comment by martinroddam** [comment]
It's a great addition, but please note that there appears to be an issue with comments in `RECORD` fields. Raised an issue [here](https://github.com/chuhlomin/protoc-gen-bq-schema/issues/2).

**Comment by mescanne** [comment]
Konstantin -- we're looking to start maintaining this repo again. As you've forked it, do you have any interest in continuing to contribute? Thanks.

**Comment by mescanne** [comment]
I've tested out this change and am happy with it, but would like to update the examples to include descriptions. I'm merging it now and will add that on.

**Pull request merged**
