### PR TITLE
Upgrade dependencies and deprecated Go module

### PR DESCRIPTION
**Pull request by mfridman**
This PR does a few things, but the ultimate goal is to deprecate the older Go module:

```
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
```

1. Replace types for their equivalent google.golang.org/protobuf counterparts
2. Update go.mod deps and tidy
3. Re-generate the examples in ./protos directory with the latest `protoc` version (26.1) and the latest `protoc-gen-go` version (v1.33.0).
4. Update Makefile
5. Bumps go version to 1.16 (from 1.15), to use `io.ReadAll` (`ioutil` was deprecated). 
6. Bumps GitHub actions to the latest major workflows

cc @mescanne wdyt about also tagging a semver release like `v1.1.0`?

### CODE REVIEW

**Comment by mescanne** [comment]
Looks good to me. New semver release also makes sense.

**Comment by mfridman** [comment]
Awesome, thanks for taking a look. I'm happy to help address outstanding issues or make incremental improvements if you're up for a few reviews.

Also, thank you for publishing a new release 🙌 .

**Comment by mescanne** [comment]
I'm currently really maxed out... I'll see what I can. My main concern is not breaking existing functionality. But it's better to keep code in a single place rather than having multiple forks if possible.

**Comment by mfridman** [comment]
No worries, appreciate you still maintaining the project and willing to make forward progress.

**Pull request merged**
