### PR TITLE
Add example of overwriting type

### PR DESCRIPTION
**Pull request by JacobSMoller**

### CODE REVIEW

**Comment by JacobSMoller** [comment]
@googlebot I signed it!

**Comment by JacobSMoller** [comment]
Not a lot to say here really. I just had to look into https://github.com/GoogleCloudPlatform/protoc-gen-bq-schema/blob/master/bq_field.proto to find the type_override option and figured if anyone else ever needed it, it might as well be in the README.

**Comment by mescanne** [comment]
Jacob -- looking to start maintaining this again. Still interested in pursuing this pullrequest?

**Comment by mescanne** [comment]
Jacob -- looking at this the README.md has already been updated to include an example of this. Thanks for the pullrequest!

**Pull request closed without merging**
