### PR TITLE
Adding PolicyTags Support

### PR DESCRIPTION
**Pull request by Harsh-Git-Hub**
### Updates:

1.  Added policy_tags definition in `bq_field.proto`.
2. Created `struct` defining the structure of PolicyTags and modified the `struct Fields` to include PolicyTags in `main.go`.
3. Added logic to convert PolicyTags into JSON schema (ConvertField in `main.go`)
4. Created tests in `field_option_test.go` to test policy tags generation.
5. Added test file: `test_table.proto` file for testing.

This version of `protoc-gen-bq-schema` will generate a JSON schema with the provided policy tag string. 

> Note: The policy tag string is considered as provided. So please provide a valid policyTag string. 

BigQuery expects the policyTag string to be of the following format: 
`projects/project-id/locations/location/taxonomies/taxonomy-id/policyTags/policytag-id`. 

Refer [Google Docs](https://cloud.google.com/bigquery/docs/column-level-security-intro) for guidelines on creating policy tags string.

### Example Usage:

Suppose you have defined the test_table.proto file as:

```
syntax = "proto3";
package foo;
import "bq_table.proto";
import "bq_field.proto";

message TestTable{
   option (gen_bq_schema.bigquery_opts).table_name = "test_table";

   int32 a = 1 [
       (gen_bq_schema.bigquery) = {
         require: true
         policy_tags : "private"
       }
     ];
  
   string b = 2 [(gen_bq_schema.bigquery).policy_tags="public"];

   message Nested {
       int32 a = 1 [(gen_bq_schema.bigquery) = {
           require: true
           policy_tags : "private"
           }
       ];

       string b= 2;
   }

   repeated Nested nested = 3 [(gen_bq_schema.bigquery).require = true];

   message EmptyMessage {}

   repeated EmptyMessage hasMessage = 4;
}
```

Running `protoc –bq-schema_out=$SRC_DIR $SRC_DIR/test_table.proto` will generate a file named `foo/test_table.schema`. This schema file will contain the policyTag defined in `test_table.proto`.

```
[
{
 "name": "a",
 "type": "INTEGER",
 "mode": "REQUIRED",
 "policyTags": {
  "names": [
   "private"
  ]
 }
},
{
 "name": "b",
 "type": "STRING",
 "mode": "NULLABLE",
 "policyTags": {
  "names": [
   "public"
  ]
 }
},
{
 "name": "nested",
 "type": "RECORD",
 "mode": "REQUIRED",
 "fields": [
  {
   "name": "a",
   "type": "INTEGER",
   "mode": "REQUIRED",
   "policyTags": {
    "names": [
     "private"
    ]
   }
  },
  {
   "name": "b",
   "type": "STRING",
   "mode": "NULLABLE"
  }
 ]
}
]
```

> Note: Empty messages will be ignored.

### CODE REVIEW

**Comment by mescanne** [comment]
I've had a brief read through it and I like it. The lint has some issues -- go mod tidy, go fmt -- which I can have a look at.

Will there be an issue with the CLA?

Thanks.

**Comment by Harsh-Git-Hub** [comment]
@mescanne I have added the CLA and rescanned the PR.

**Comment by mescanne** [comment]
Thanks -- it's go.sum that go vet is complaining about. Likely a newline at the end is missing or needs to be added. That's all that's missing!

**Comment by Harsh-Git-Hub** [comment]
@mescanne Updated the PR. Seems like there are no conflicts.

**Comment by mescanne** [comment]
Good -- there's just one more thing. I don't think you've run "go mod tidy" on your code. There are extra modules in go.sum. Would you mind doing that as well?

Thanks.

**Comment by Harsh-Git-Hub** [comment]
Thanks for the information. Updated the PR.

**Comment by mescanne** [comment]
Thanks a lot -- much appreciated!

**Pull request merged**
