### PR TITLE
Add support for message-level extra_fields

### PR DESCRIPTION
**Pull request by chuhlomin**
This PR adds support for "extra_fields" message-level custom option that allows defining artificial fields that has to be added to BigQuery schema (but not to be exposed to other schema-users).

For example:
```proto
message Bar {
  option (gen_bq_schema.bigquery_opts).table_name = "bar_table";
  option (gen_bq_schema.bigquery_opts).extra_fields = "i2:INTEGER";
  option (gen_bq_schema.bigquery_opts).extra_fields = "i3:TIMESTAMP";

  string i1 = 1;
}
```
will result in this BQ schema:
```json
[
  { "name": "i1", "type": "STRING", "mode": "NULLABLE" },
  { "name": "i2", "type": "INTEGER", "mode": "NULLABLE" },
  { "name": "i3", "type": "TIMESTAMP", "mode": "NULLABLE" },
]
```
(see more examples in plugin_test.go)

### CODE REVIEW

**Comment by sdotz** [comment]
Using this right now Konstantin

**Comment by shreelekha** [comment]
Hello! we use this message level `extra_fields`. Is it possible to get these changes merged?

**Comment by sbower** [comment]
@mescanne This would be super helpful, would be great to get it merged

**Comment by mescanne** [comment]
This is now merged.  Are you using the latest master or a release? I'm going to assume master branch in which case it should be there now.

**Pull request merged**
