### PR TITLE
Migrate to Github Actions and minor cleanup of code formatting/dependencies

### PR DESCRIPTION
**Pull request by mescanne**
Initial

### CODE REVIEW

**Comment by mescanne** [comment]
Github Actions are the preferred approach and adding CI for format check, mod tidy check, test, and building.

**Comment by mescanne** [comment]
Okay -- now it's working and it also re-generates the examples and fails if they're different.

**Comment by mescanne** [comment]
Updated the GitHub actions for both examples.

**Review by thinhha — APPROVED** [review]
lgtm

**Pull request merged**
